### ISSUE TITLE
Exception in thread "Thread-3" java.lang.UnsatisfiedLinkError: lib: libsystemhook-linux-amd64.so not found in lib directory

### ISSUE THREAD

**Issue by LevkinSergey** [otymko/phoenixbsl#106]
При попытке запустить на линуксе инструмент запускается, но клавиши не отлавливаются.

linux mint 20 
java liberica 11.0.6 2020-01-15 LTS

В логах консоли пишет следующее. 

Exception in thread "Thread-3" java.lang.UnsatisfiedLinkError: lib: libsystemhook-linux-amd64.so not found in lib directory
	at lc.kra.system.LibraryLoader.loadLibrary(LibraryLoader.java:86)
	at lc.kra.system.keyboard.GlobalKeyboardHook.<init>(GlobalKeyboardHook.java:113)
	at lc.kra.system.keyboard.GlobalKeyboardHook.<init>(GlobalKeyboardHook.java:101)
	at org.github.otymko.phoenixbsl.threads.GlobalKeyListenerThread.runHook(GlobalKeyListenerThread.java:52)
	at org.github.otymko.phoenixbsl.threads.GlobalKeyListenerThread.run(GlobalKeyListenerThread.java:42)

**Comment by nixel2007** [comment]
Насколько я помню, феникс использует WinApi и не может работать в linux вовсе

**Comment by LevkinSergey** [comment]
очень жаль. Думал на java, значит можно попробовать.

**Comment by nixel2007** [comment]
Оно-то на java, но есть вот такое:

https://github.com/otymko/phoenixbsl/blob/develop/src/main/java/com/github/otymko/phoenixbsl/PhoenixCore.java#L13

Возможно в будущем получится делать перехватчики клавиатуры хотя бы под linux. Пока грубо говоря запросов таких не было, ты первый :)

**Comment by LevkinSergey** [comment]
буду ждать и надеться, когда версия для линукса появится

**Comment by otymko** [comment]
@LevkinSergey по идее можно подумать над этим. Т.к. проект использует не так много функций, привязанных к WIN. По факту используется:
- Глобальный слушатель нажатий кнопок
- Перехват свойств открытых окон.
