### ISSUE TITLE
Работает только под административными правами

### ISSUE THREAD

**Issue by KrapivinAndrey** [otymko/phoenixbsl#55]
Версия 2.2

PS C:\Users\a.krapivin\Downloads> java -version
openjdk version "11.0.5-BellSoft" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-BellSoft+11)
OpenJDK 64-Bit Server VM (build 11.0.5-BellSoft+11, mixed mode)

Первый запуск не под админскими правами - не работает.
Запустил от админа - работает.
Снова под обычными правами - работает

**Comment by otymko** [comment]
Сборка msi?

**Comment by KrapivinAndrey** [comment]
jar

**Comment by KrapivinAndrey** [comment]
[Global Keyboard Hook Dispatcher] INFO org.github.otymko.phoenixbsl.events.GlobalKeyboardHookHandler - 73 [down,control]
[AWT-EventQueue-0] INFO org.github.otymko.phoenixbsl.App - Line: 182
[AWT-EventQueue-0] INFO org.github.otymko.phoenixbsl.App - Line: 106
[AWT-EventQueue-0] INFO org.github.otymko.phoenixbsl.App - Line: 203
[Global Keyboard Hook Dispatcher] INFO org.github.otymko.phoenixbsl.events.GlobalKeyboardHookHandler - 75 [down,control,win]
Exception in thread "Global Keyboard Hook Dispatcher" java.lang.IndexOutOfBoundsException: Index: 0
        at java.base/java.util.Collections$EmptyList.get(Collections.java:4483)
        at org.github.otymko.phoenixbsl.App.runFormattingBSL(App.java:136)
        at org.github.otymko.phoenixbsl.events.GlobalKeyboardHookHandler$1.keyPressed(GlobalKeyboardHookHandler.java:57)
        at lc.kra.system.keyboard.GlobalKeyboardHook.keyPressed(GlobalKeyboardHook.java:150)
        at lc.kra.system.keyboard.GlobalKeyboardHook.access$100(GlobalKeyboardHook.java:50)
        at lc.kra.system.keyboard.GlobalKeyboardHook$1.run(GlobalKeyboardHook.java:71)
