### ISSUE TITLE
Отваливается eventListener

### ISSUE THREAD

**Issue by sfaqer** [otymko/phoenixbsl#61]
Стектрейс:
```java
Exception in thread "Global Keyboard Hook Dispatcher" [pool-1-thread-1] INFO EventManager - Событие 3
java.lang.IllegalStateException: cannot open system clipboard
        at java.desktop/sun.awt.windows.WClipboard.openClipboard(Native Method)
        at java.desktop/sun.awt.datatransfer.SunClipboard.getData(SunClipboard.java:208)
        at org.github.otymko.phoenixbsl.core.PhoenixAPI.getDataClipboard(PhoenixAPI.java:131)
        at org.github.otymko.phoenixbsl.core.PhoenixAPI.getFromClipboard(PhoenixAPI.java:115)
        at org.github.otymko.phoenixbsl.core.PhoenixAPI.getTextSelected(PhoenixAPI.java:35)
        at org.github.otymko.phoenixbsl.core.PhoenixApp.inspection(PhoenixApp.java:128)
        at org.github.otymko.phoenixbsl.events.EventManager.notify(EventManager.java:43)
        at org.github.otymko.phoenixbsl.threads.GlobalKeyListenerThread$1.keyPressed(GlobalKeyListenerThread.java:40)           at lc.kra.system.keyboard.GlobalKeyboardHook.keyPressed(GlobalKeyboardHook.java:150)
        at lc.kra.system.keyboard.GlobalKeyboardHook.access$100(GlobalKeyboardHook.java:50)
        at lc.kra.system.keyboard.GlobalKeyboardHook$1.run(GlobalKeyboardHook.java:71)
```

Сценария воспроизведения нет, может отвалится в случайные моменты, приложение продолжает работать, форточка со списком ишузов активна, можно переходить по строкам, но нажатия больше не перехватываются.

**Comment by otymko** [comment]
Принято, почему то кричит буфер обмена.

**Comment by otymko** [comment]
@sfaqer Актуальна ли проблема в сборке https://github.com/otymko/phoenixbsl/suites/420451832/artifacts/1345224 ?

**Comment by sfaqer** [comment]
@otymko ошибка сохранилась, несколько изменилось поведение. После воспроизведения значёк в трее активен, но если там кликнуть "Настройки" после отвала листенера, то окно настроек не появляется, и значёе в трее тоже больше не реагирует, менюшка не всплывает.
Если рукми прибить процесс bsl-ls то феникс оживает и продолжает работу. Логи:
[app.log](https://github.com/otymko/phoenixbsl/files/4114898/app.log)

**Comment by sfaqer** [comment]
Судя по логам я так понимаю феникс зависает в ожидании какого-то отклика от bsl-ls, и судя по всему ошибка возникает на стороне bsl-ls, можно пробросить логи bsl-ls и писать в отдельный файлик с логами?

**Comment by otymko** [comment]
@sfaqer можно пробросить. Но надо будет немного поколдовать

**Comment by sfaqer** [comment]
fixed в https://github.com/otymko/phoenixbsl/actions/runs/36139634
